# Dockerfile to develop the theme locally

version: '2'

services:
  ctfd:
    image: ctfd/ctfd
    container_name: ctfd
    hostname: ctfd
    ports:
      - 8000:8000
    environment:
      - UPLOAD_FOLDER=/var/uploads
      - WORKERS=1
      - LOG_FOLDER=/var/log/CTFd
      - ACCESS_LOG=-
      - ERROR_LOG=-
    volumes:
      # Mount the theme folder below
      - ./ftheme:/opt/CTFd/CTFd/themes/ftheme:ro
    networks:
        default:
        internal:

networks:
    default:
    internal:
      internal: true
